// Generated by Wrangler by running `wrangler types --experimental-include-runtime`

import { KVNamespace } from "@cloudflare/workers-types/experimental";

export interface Env {
  SHORTLINKS: KVNamespace;
}
